CREATE TABLE IF NOT EXISTS "roles" (
  "id" bigint PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "domains" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role_id" bigint NOT NULL,
  "domain_id" bigint,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE IF NOT EXISTS "companies" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "domain_id" bigint
);

CREATE TABLE IF NOT EXISTS "projects" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "company_id" bigint,
  "created_by" bigint,
  "created_at" timestamp
);

CREATE TABLE IF NOT EXISTS "project_members" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "created_at" timestamp,
  CONSTRAINT "uq_project_members_project_user" UNIQUE ("project_id", "user_id")
);

CREATE TABLE IF NOT EXISTS "task_status" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "priorities" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" int NOT NULL,
  "label" varchar
);

CREATE TABLE IF NOT EXISTS "tasks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" bigint NOT NULL,
  "title" varchar NOT NULL,
  "description" text,
  "assigned_to" bigint,
  "status_id" bigint,
  "priority_id" bigint,
  "created_by" bigint,
  "due_date" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE IF NOT EXISTS "comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" bigint NOT NULL,
  "author_id" bigint NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp
);

CREATE TABLE IF NOT EXISTS "attachments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" bigint NOT NULL,
  "uploaded_by" bigint,
  "file_path" varchar NOT NULL,
  "created_at" timestamp
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "users" ADD FOREIGN KEY ("domain_id") REFERENCES "domains" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "companies" ADD FOREIGN KEY ("domain_id") REFERENCES "domains" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "projects" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "projects" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "project_members" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "project_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks" ADD FOREIGN KEY ("assigned_to") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks" ADD FOREIGN KEY ("status_id") REFERENCES "task_status" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks" ADD FOREIGN KEY ("priority_id") REFERENCES "priorities" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "tasks" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "comments" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "comments" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "attachments" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "attachments" ADD FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
