CREATE TABLE IF NOT EXISTS "roles" (
  "id"   bigint PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "domains" (
  "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "users" (
  "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username"   varchar NOT NULL,
  "email"      varchar UNIQUE NOT NULL,
  "password"   varchar NOT NULL,
  "role_id"    bigint NOT NULL REFERENCES "roles"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "domain_id"  bigint REFERENCES "domains"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE IF NOT EXISTS "companies" (
  "id"        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"      varchar NOT NULL,
  "domain_id" bigint REFERENCES "domains"("id") DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS "projects" (
  "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"       varchar NOT NULL,
  "company_id" bigint REFERENCES "companies"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "created_by" bigint REFERENCES "users"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "created_at" timestamp
);

CREATE TABLE IF NOT EXISTS "project_members" (
  "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" bigint NOT NULL REFERENCES "projects"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "user_id"    bigint NOT NULL REFERENCES "users"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "created_at" timestamp,
  CONSTRAINT "uq_project_members_project_user" UNIQUE ("project_id", "user_id")
);

CREATE TABLE IF NOT EXISTS "task_status" (
  "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "priorities" (
  "id"    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" int NOT NULL,
  "label" varchar
);

CREATE TABLE IF NOT EXISTS "tasks" (
  "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id"  bigint NOT NULL REFERENCES "projects"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "title"       varchar NOT NULL,
  "description" text,
  "assigned_to" bigint REFERENCES "users"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "status_id"   bigint REFERENCES "task_status"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "priority_id" bigint REFERENCES "priorities"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "created_by"  bigint REFERENCES "users"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "due_date"    timestamp,
  "created_at"  timestamp,
  "updated_at"  timestamp
);

CREATE TABLE IF NOT EXISTS "comments" (
  "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id"    bigint NOT NULL REFERENCES "tasks"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "author_id"  bigint NOT NULL REFERENCES "users"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "content"    text NOT NULL,
  "created_at" timestamp
);

CREATE TABLE IF NOT EXISTS "attachments" (
  "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id"     bigint NOT NULL REFERENCES "tasks"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "uploaded_by" bigint REFERENCES "users"("id") DEFERRABLE INITIALLY IMMEDIATE,
  "file_path"   varchar NOT NULL,
  "created_at"  timestamp
);
